# Generated by Django 4.2.7 on 2025-08-21 10:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Contact Us', max_length=255)),
                ('title_uk', models.CharField(default="Зв'язатися з нами", max_length=255)),
                ('title_pl', models.CharField(default='Skontaktuj się z nami', max_length=255)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_uk', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_pl', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('email', models.EmailField(default='info@lazysoft.pl', max_length=254)),
                ('phone', models.CharField(default='+48 727 842 737', max_length=50)),
                ('address_line_1_en', models.CharField(default='EU R&D Centre', max_length=255)),
                ('address_line_1_uk', models.CharField(default='Центр досліджень ЄС', max_length=255)),
                ('address_line_1_pl', models.CharField(default='Centrum Badawcze UE', max_length=255)),
                ('address_line_2', models.CharField(default='Social links Latvia, SIA.', max_length=255)),
                ('address_line_3', models.CharField(default='Ganibu dambis 26A', max_length=255)),
                ('city', models.CharField(default='Riga', max_length=100)),
                ('postal_code', models.CharField(default='LV 1005', max_length=20)),
                ('country_en', models.CharField(default='Latvia', max_length=100)),
                ('country_uk', models.CharField(default='Латвія', max_length=100)),
                ('country_pl', models.CharField(default='Łotwa', max_length=100)),
                ('google_maps_url', models.URLField(blank=True, default='https://share.google/3MQpGv5E0z1wUEI8H', help_text='Посилання на Google Maps', null=True)),
                ('office_photo', models.ImageField(blank=True, null=True, upload_to='contacts/office/')),
                ('is_active', models.BooleanField(default=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=255)),
                ('seo_title_uk', models.CharField(blank=True, max_length=255)),
                ('seo_title_pl', models.CharField(blank=True, max_length=255)),
                ('seo_description_en', models.TextField(blank=True, max_length=300)),
                ('seo_description_uk', models.TextField(blank=True, max_length=300)),
                ('seo_description_pl', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('referred_from', models.CharField(blank=True, help_text='Наприклад: service_ai_automation, project_chatbot_analytics', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
