# Generated by Django 4.2.7 on 2025-08-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_line_3',
        ),
        migrations.AddField(
            model_name='contact',
            name='hero_photo',
            field=models.ImageField(blank=True, help_text='Головне фото для Hero секції', null=True, upload_to='contacts/hero/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(default='Wrocław', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country_en',
            field=models.CharField(default='Poland', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country_pl',
            field=models.CharField(default='Polska', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country_uk',
            field=models.CharField(default='Польща', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='hello@lazysoft.dev', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='google_maps_url',
            field=models.URLField(blank=True, default='https://maps.google.com/maps?q=Wrocław,+Poland', help_text='Посилання на Google Maps', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='postal_code',
            field=models.CharField(default='51-664', max_length=20),
        ),
    ]
