# Generated by Django 4.2.7 on 2025-08-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_address_line_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='hero_description_en',
            field=models.TextField(default='Modern office where ideas are born and the most ambitious projects come to life. Here we create the future together with our clients.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='hero_description_pl',
            field=models.TextField(default='Nowoczesne biuro, gdzie rodzą się pomysły i realizowane są najbardziej śmiałe projekty. Tutaj tworzymy przyszłość razem z naszymi klientami.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='hero_description_uk',
            field=models.TextField(default='Сучасний офіс, де народжуються ідеї та втілюються найсміливіші проєкти. Тут ми створюємо майбутнє разом з нашими клієнтами.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='hero_title_en',
            field=models.CharField(default='Our Space for Innovation', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='hero_title_pl',
            field=models.CharField(default='Nasza przestrzeń do innowacji', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='hero_title_uk',
            field=models.CharField(default='Наш простір для інновацій', max_length=255),
        ),
    ]
