# Generated by Django 4.2.7 on 2025-09-08 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0003_contact_hero_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лід/Заявка', 'verbose_name_plural': 'Ліди/Заявки'},
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Призначено менеджеру'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Очікуваний бюджет'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True, verbose_name='Очікувана дата закриття'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Остання взаємодія'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='lead_score',
            field=models.IntegerField(default=0, help_text='Оцінка ліда 0-100', verbose_name='Оцінка ліда'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='lead_source',
            field=models.CharField(choices=[('website', 'Сайт'), ('social_media', 'Соціальні мережі'), ('referral', 'Рекомендація'), ('advertising', 'Реклама'), ('cold_outreach', 'Холодні дзвінки'), ('other', 'Інше')], default='website', max_length=50, verbose_name='Джерело ліда'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='next_follow_up',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Наступний follow-up'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'Новий лід'), ('contacted', "Зв'язались"), ('qualified', 'Кваліфікований'), ('proposal_sent', 'Відправлено пропозицію'), ('negotiation', 'Переговори'), ('closed_won', 'Закрито успішно'), ('closed_lost', 'Закрито неуспішно')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
