# Generated by Django 4.2.7 on 2025-09-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contactsubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='asana_task_id',
            field=models.CharField(blank=True, help_text='ID таска в Asana для відстеження', max_length=50, null=True),
        ),
    ]
