# Generated by Django 4.2.7 on 2025-09-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contactsubmission_asana_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='cta_source',
            field=models.CharField(blank=True, help_text='Джерело CTA кнопки (наприклад: service_detail, project_detail, footer_cta)', max_length=50, null=True, verbose_name='CTA джерело'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='page_url',
            field=models.URLField(blank=True, help_text='URL сторінки з якої була відправлена форма', null=True, verbose_name='URL сторінки'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='session_id',
            field=models.CharField(blank=True, help_text='ID сесії користувача для відстеження', max_length=40, null=True, verbose_name='ID сесії'),
        ),
    ]
