# Generated by Django 4.2.7 on 2025-09-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contactsubmission_cta_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='LAZYSOFT', max_length=255)),
                ('website', models.URLField(default='lazysoft.dev')),
                ('logo', models.ImageField(blank=True, help_text='Лого компанії для документів', null=True, upload_to='company/logos/')),
                ('address_line1', models.CharField(default='Edwarda Dembowskiego 98/1', max_length=255)),
                ('city', models.CharField(default='Wrocław', max_length=100)),
                ('postal_code', models.CharField(default='51-669', max_length=20)),
                ('country', models.CharField(default='Poland', max_length=100)),
                ('email', models.EmailField(default='dchuprina@lazysoft.pl', max_length=254)),
                ('phone', models.CharField(default='+48 727 842 737', max_length=50)),
                ('tax_id', models.CharField(blank=True, help_text='NIP/Tax ID', max_length=50)),
                ('authorized_person', models.CharField(default='Daria Chuprina', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
    ]
