# Generated by Django 5.0.14 on 2025-09-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='website',
            field=models.CharField(blank=True, help_text='Honeypot field - should always be empty', max_length=255, null=True),
        ),
    ]
