# Generated by Django 4.2.7 on 2025-10-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contactsubmission_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='signature',
            field=models.ImageField(blank=True, help_text='Підпис для документів (PNG)', null=True, upload_to='company/signatures/'),
        ),
    ]
