# Generated by Django 4.2.7 on 2025-08-05 09:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0009_alter_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255)),
                ('title_pl', models.CharField(max_length=255)),
                ('short_description_en', ckeditor.fields.RichTextField(blank=True, help_text='Короткий опис для відображення в картках', null=True)),
                ('short_description_uk', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('short_description_pl', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('client_request_en', ckeditor.fields.RichTextField(help_text='Що хотів клієнт, яка була задача')),
                ('client_request_uk', ckeditor.fields.RichTextField()),
                ('client_request_pl', ckeditor.fields.RichTextField()),
                ('implementation_en', ckeditor.fields.RichTextField(help_text='Як було реалізовано, які технології використали')),
                ('implementation_uk', ckeditor.fields.RichTextField()),
                ('implementation_pl', ckeditor.fields.RichTextField()),
                ('results_en', ckeditor.fields.RichTextField(help_text='Яких результатів досяг клієнт, економія часу/грошей')),
                ('results_uk', ckeditor.fields.RichTextField()),
                ('results_pl', ckeditor.fields.RichTextField()),
                ('featured_image', models.ImageField(blank=True, help_text='Основне зображення проєкту', null=True, upload_to='projects/images/')),
                ('gallery_image_1', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('gallery_image_2', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('gallery_image_3', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo або інший URL', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Або завантажте відео файл', null=True, upload_to='projects/videos/')),
                ('technologies_used', models.CharField(blank=True, help_text='Список технологій через кому: Python, Django, React, OpenAI', max_length=500, null=True)),
                ('project_url', models.URLField(blank=True, help_text='Посилання на готовий проєкт', null=True)),
                ('seo_title_en', models.CharField(max_length=255)),
                ('seo_title_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_pl', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description_en', models.TextField(max_length=300)),
                ('seo_description_uk', models.TextField(blank=True, max_length=300, null=True)),
                ('seo_description_pl', models.TextField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Показувати на головній сторінці')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок відображення')),
                ('project_date', models.DateField(help_text='Коли був виконаний проєкт')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Категорія сервісу, до якої належить проєкт', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-order', '-project_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text="Ім'я клієнта (може бути псевдонім)", max_length=255)),
                ('client_position', models.CharField(blank=True, help_text='Посада в компанії', max_length=255, null=True)),
                ('client_company', models.CharField(blank=True, help_text='Назва компанії', max_length=255, null=True)),
                ('client_avatar', models.ImageField(blank=True, null=True, upload_to='projects/reviews/')),
                ('review_text_en', ckeditor.fields.RichTextField()),
                ('review_text_uk', ckeditor.fields.RichTextField()),
                ('review_text_pl', ckeditor.fields.RichTextField()),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Рейтинг від 1 до 5 зірок')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Review',
                'verbose_name_plural': 'Project Reviews',
            },
        ),
        migrations.CreateModel(
            name='ProjectContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_submissions', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Contact Submission',
                'verbose_name_plural': 'Project Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
