# Generated by Django 4.2.7 on 2025-08-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-priority', '-order', '-project_date'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('small', '💰 $1k-5k'), ('medium', '💰💰 $5k-15k'), ('large', '💰💰💰 $15k-50k'), ('enterprise', '💰💰💰💰 $50k+'), ('custom', '🤝 Custom')], help_text='Приблизний діапазон бюджету проєкту', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_time_saved_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Скільки годин на тиждень економить клієнт', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='complexity_level',
            field=models.PositiveIntegerField(choices=[(1, '⭐ Simple - Простий'), (2, '⭐⭐ Medium - Середній'), (3, '⭐⭐⭐ Complex - Складний'), (4, '⭐⭐⭐⭐ Enterprise - Корпоративний'), (5, '⭐⭐⭐⭐⭐ Cutting Edge - Передовий')], default=2, help_text='Рівень складності проєкту (впливає на яскравість ефектів та свічення)'),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_badge_color',
            field=models.CharField(choices=[('green', 'Зелений 🟢'), ('blue', 'Синій 🔵'), ('purple', 'Фіолетовий 🟣'), ('orange', 'Помаранчевий 🟠'), ('red', 'Червоний 🔴'), ('gold', 'Золотий 🟡'), ('pink', 'Рожевий \U0001fa77'), ('cyan', 'Бірюзовий 🔷')], default='green', help_text='Колір для кастомного бейджа', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_badge_en',
            field=models.CharField(blank=True, help_text='Кастомний бейдж (наприклад: EXCLUSIVE, PREMIUM, тощо)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_badge_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_badge_uk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='development_duration_weeks',
            field=models.PositiveIntegerField(blank=True, help_text='Скільки тижнів тривала розробка', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_ai_powered',
            field=models.BooleanField(default=False, help_text="Показувати фіолетовий бейдж 'AI POWERED'"),
        ),
        migrations.AddField(
            model_name='project',
            name='is_complex',
            field=models.BooleanField(default=False, help_text="Показувати бейдж 'COMPLEX'"),
        ),
        migrations.AddField(
            model_name='project',
            name='is_enterprise',
            field=models.BooleanField(default=False, help_text="Показувати бейдж 'ENTERPRISE'"),
        ),
        migrations.AddField(
            model_name='project',
            name='is_innovative',
            field=models.BooleanField(default=False, help_text="Показувати синій бейдж 'INNOVATIVE'"),
        ),
        migrations.AddField(
            model_name='project',
            name='is_top_project',
            field=models.BooleanField(default=False, help_text="Показувати золотий бейдж 'TOP'"),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'Низький'), (2, 'Звичайний'), (3, 'Високий'), (4, 'Критичний'), (5, 'Топ проєкт')], default=2, help_text='Пріоритет проєкту (впливає на порядок та яскравість відображення)'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('completed', '✅ Завершено'), ('ongoing', '🔄 В процесі'), ('maintenance', '🔧 Підтримка'), ('paused', '⏸️ Призупинено'), ('archived', '📦 Архівовано')], default='completed', help_text='Поточний статус проєкту', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_en',
            field=models.CharField(blank=True, help_text='Fintech Automation, E-commerce, AI Chat Bot, тощо', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_pl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_uk',
            field=models.CharField(blank=True, help_text='Фінтех автоматизація, Електронна комерція, ШІ чат-бот, тощо', max_length=100, null=True),
        ),
    ]
