# Generated by Django 4.2.7 on 2025-08-12 13:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_project_budget_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges_and_solutions_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Які були виклики під час розробки і як їх вирішили', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges_and_solutions_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges_and_solutions_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_request_extended_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Детальний запит клієнта для сторінки проєкту (може містити скріншоти, діаграми)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_request_extended_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_request_extended_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='implementation_extended_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Детальна реалізація з технічними деталями, архітектурою, процесом розробки', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='implementation_extended_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='implementation_extended_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons_learned_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Що вивчили під час проєкту, поради для майбутніх проєктів', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons_learned_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons_learned_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='results_extended_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Детальні результати з метриками, графіками, статистикою', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='results_extended_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='results_extended_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
