# Generated by Django 4.2.7 on 2025-08-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0003_project_challenges_and_solutions_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Внутрішні теги для крос-видачі з новинами та сервісами', related_name='projects', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type_en',
            field=models.CharField(blank=True, help_text='DEPRECATED: Використовуй нову систему тегів. Fintech Automation, E-commerce, AI Chat Bot, тощо', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type_pl',
            field=models.CharField(blank=True, help_text='DEPRECATED: Використовуй нову систему тегів', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type_uk',
            field=models.CharField(blank=True, help_text='DEPRECATED: Використовуй нову систему тегів. Фінтех автоматизація, Електронна комерція, ШІ чат-бот, тощо', max_length=100, null=True),
        ),
    ]
