# Generated by Django 4.2.7 on 2025-09-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_service_category'),
        ('projects', '0004_project_tags_alter_project_project_type_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default=5, help_text='Категорія сервісу, до якої належить проєкт', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='services.servicecategory'),
            preserve_default=False,
        ),
    ]
