# Generated by Django 5.0.14 on 2025-09-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Зображення для соцмереж (1200x630px)', null=True, upload_to='projects/og/'),
        ),
    ]
