# Generated by Django 4.2.7 on 2025-08-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROIAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('manual_hours_saved', models.FloatField(default=0, verbose_name='Годин заощаджено (ручна робота)')),
                ('ai_processing_time', models.FloatField(default=0, verbose_name='Час AI обробки (годин)')),
                ('time_efficiency', models.FloatField(default=0, verbose_name='Ефективність часу (%)')),
                ('content_manager_cost_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Економія на контент-менеджері')),
                ('smm_specialist_cost_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Економія на SMM')),
                ('copywriter_cost_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Економія на копірайтері')),
                ('ai_api_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Витрати на AI API')),
                ('net_savings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Чиста економія')),
                ('organic_traffic_increase', models.IntegerField(default=0, verbose_name='Приріст органічного трафіку')),
                ('social_engagement_increase', models.IntegerField(default=0, verbose_name='Приріст engagement соцмереж')),
                ('new_leads_generated', models.IntegerField(default=0, verbose_name='Нових лідів згенеровано')),
                ('bounce_rate_improvement', models.FloatField(default=0, verbose_name='Покращення bounce rate (%)')),
                ('articles_processed', models.IntegerField(default=0, verbose_name='Статей оброблено AI')),
                ('translations_made', models.IntegerField(default=0, verbose_name='Перекладів зроблено')),
                ('social_posts_generated', models.IntegerField(default=0, verbose_name='Соцмереж постів згенеровано')),
                ('images_generated', models.IntegerField(default=0, verbose_name='AI зображень згенеровано')),
                ('avg_article_rating', models.FloatField(default=0, verbose_name='Середня оцінка статей')),
                ('seo_score_improvement', models.FloatField(default=0, verbose_name='Покращення SEO скору')),
                ('content_uniqueness', models.FloatField(default=0, verbose_name='Унікальність контенту (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'ROI Аналітика',
                'verbose_name_plural': 'ROI Аналітика',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DashboardProxy',
            fields=[
            ],
            options={
                'verbose_name': '🚀 LAZYSOFT Dashboard',
                'verbose_name_plural': '🚀 LAZYSOFT Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.processedarticle',),
        ),
        migrations.CreateModel(
            name='NewsWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва віджета')),
                ('widget_type', models.CharField(choices=[('latest', 'Останні новини'), ('trending', 'Популярні новини'), ('category', 'По категорії'), ('featured', 'Рекомендовані')], max_length=20, verbose_name='Тип віджета')),
                ('articles_limit', models.IntegerField(default=5, verbose_name='Кількість статей')),
                ('show_images', models.BooleanField(default=True, verbose_name='Показувати зображення')),
                ('show_date', models.BooleanField(default=True, verbose_name='Показувати дату')),
                ('show_category', models.BooleanField(default=True, verbose_name='Показувати категорію')),
                ('languages', models.JSONField(default=list, verbose_name='Мови')),
                ('css_class', models.CharField(blank=True, max_length=100, verbose_name='CSS клас')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Колір фону')),
                ('text_color', models.CharField(default='#333333', max_length=7, verbose_name='Колір тексту')),
                ('position', models.IntegerField(default=0, verbose_name='Позиція на сторінці')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('categories', models.ManyToManyField(blank=True, to='news.newscategory', verbose_name='Категорії')),
            ],
            options={
                'verbose_name': 'Віджет новин',
                'verbose_name_plural': 'Віджети новин',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram_uk', 'Telegram Ukraine'), ('instagram_pl', 'Instagram Poland'), ('facebook_pl', 'Facebook Poland'), ('instagram_en', 'Instagram English'), ('facebook_en', 'Facebook English'), ('linkedin_en', 'LinkedIn English')], max_length=20, verbose_name='Платформа')),
                ('content', models.TextField(verbose_name='Текст поста')),
                ('hashtags', models.CharField(blank=True, max_length=500, verbose_name='Хештеги')),
                ('image_url', models.URLField(blank=True, verbose_name='Зображення')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Заплановано на')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубліковано')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('scheduled', 'Заплановано'), ('published', 'Опубліковано'), ('failed', 'Помилка')], default='draft', max_length=20, verbose_name='Статус')),
                ('external_post_id', models.CharField(blank=True, max_length=100, verbose_name='ID в соцмережі')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Лайків')),
                ('comments_count', models.IntegerField(default=0, verbose_name='Коментарів')),
                ('shares_count', models.IntegerField(default=0, verbose_name='Поділилися')),
                ('reach_count', models.IntegerField(default=0, verbose_name='Охоплення')),
                ('error_message', models.TextField(blank=True, verbose_name='Помилка')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Спроб публікації')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='news.processedarticle')),
            ],
            options={
                'verbose_name': 'Пост в соцмережі',
                'verbose_name_plural': 'Пости в соцмережах',
                'ordering': ['-created_at'],
                'unique_together': {('article', 'platform')},
            },
        ),
    ]
