# Generated by Django 4.2.7 on 2025-08-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_roianalytics_dashboardproxy_newswidget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roianalytics',
            name='key_takeaways_en',
            field=models.JSONField(default=list, verbose_name='Ключові висновки (EN)'),
        ),
        migrations.AddField(
            model_name='roianalytics',
            name='key_takeaways_pl',
            field=models.JSONField(default=list, verbose_name='Ключові висновки (PL)'),
        ),
        migrations.AddField(
            model_name='roianalytics',
            name='key_takeaways_uk',
            field=models.JSONField(default=list, verbose_name='Ключові висновки (UK)'),
        ),
    ]
