# Generated by Django 4.2.7 on 2025-08-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_roianalytics_key_takeaways_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedarticle',
            name='business_opportunities_en',
            field=models.TextField(blank=True, verbose_name='Бізнес можливості (EN)'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='business_opportunities_pl',
            field=models.TextField(blank=True, verbose_name='Бізнес можливості (PL)'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='business_opportunities_uk',
            field=models.TextField(blank=True, verbose_name='Бізнес можливості (UK)'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='full_content_parsed',
            field=models.BooleanField(default=False, verbose_name='Повний контент спарсений'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='interesting_facts_en',
            field=models.JSONField(default=list, verbose_name='Цікавинки (EN)'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='interesting_facts_pl',
            field=models.JSONField(default=list, verbose_name='Цікавинки (PL)'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='interesting_facts_uk',
            field=models.JSONField(default=list, verbose_name='Цікавинки (UK)'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='lazysoft_recommendations_en',
            field=models.TextField(blank=True, verbose_name='Рекомендації LAZYSOFT (EN)'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='lazysoft_recommendations_pl',
            field=models.TextField(blank=True, verbose_name='Рекомендації LAZYSOFT (PL)'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='lazysoft_recommendations_uk',
            field=models.TextField(blank=True, verbose_name='Рекомендації LAZYSOFT (UK)'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='original_word_count',
            field=models.IntegerField(default=0, verbose_name='Кількість слів оригіналу'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='reading_time',
            field=models.IntegerField(default=5, verbose_name='Час читання (хв)'),
        ),
    ]
