# Generated by Django 4.2.7 on 2025-08-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_processedarticle_business_opportunities_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedarticle',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='processedarticle',
            name='news_proces_status_f5ba22_idx',
        ),
        migrations.RemoveIndex(
            model_name='processedarticle',
            name='news_proces_publish_878246_idx',
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='article_rank',
            field=models.IntegerField(blank=True, help_text='Позиція статті в топ-5 (1-5)', null=True, verbose_name='Ранг у топ-5'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='full_content_en',
            field=models.TextField(blank=True, verbose_name='Повний контент (EN)'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='full_content_pl',
            field=models.TextField(blank=True, verbose_name='Повний контент (PL)'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='full_content_uk',
            field=models.TextField(blank=True, verbose_name='Повний контент (UK)'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='is_top_article',
            field=models.BooleanField(default=False, verbose_name='Топ стаття'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='relevance_score',
            field=models.FloatField(blank=True, help_text='Скор від AudienceAnalyzer (1-10)', null=True, verbose_name='Скор релевантності'),
        ),
        migrations.AddField(
            model_name='processedarticle',
            name='top_selection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата відбору в топ'),
        ),
    ]
