# Generated by Django 4.2.7 on 2025-08-13 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def backfill_unique_slugs(apps, schema_editor):
    Article = apps.get_model('news', 'ProcessedArticle')
    for obj in Article.objects.all().only(
        'id', 'uuid', 'slug', 'meta_title_uk', 'title_uk', 'title_en', 'title_pl'
    ):
        if obj.slug:
            continue
        base = (obj.meta_title_uk or obj.title_uk or obj.title_en or obj.title_pl or '')[:180]
        if not base:
            base = f"article-{obj.uuid}"
        slug = slugify(f"{base}-{str(obj.uuid)[:8]}")
        # про всяк — унікалізація на випадок колізій
        orig = slug
        i = 1
        while Article.objects.filter(slug=slug).exists():
            slug = f"{orig}-{i}"
            i += 1
        obj.slug = slug
        obj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_alter_processedarticle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram')], default='email', max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('body', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DashboardProxy',
        ),
        migrations.CreateModel(
            name='NewsSystemAnalytics',
            fields=[],
            options={
                'verbose_name': '🚀 News System Analytics',
                'verbose_name_plural': '🚀 News System Analytics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.processedarticle',),
        ),
        migrations.AlterModelOptions(
            name='processedarticle',
            options={
                'ordering': ['-is_top_article', '-article_rank', '-priority', '-created_at'],
                'verbose_name': 'Оброблена стаття',
                'verbose_name_plural': 'Оброблені статті'
            },
        ),
        migrations.AddField(
            model_name='newswidget',
            name='show_cross_promotion',
            field=models.BooleanField(default=False, verbose_name='Показувати крос-промоцію'),
        ),
        migrations.AddField(
            model_name='newswidget',
            name='show_tags',
            field=models.BooleanField(default=False, verbose_name='Показувати теги'),
        ),

        # --- КРОК 1: додаємо slug без unique, дозволяємо NULL ---
        migrations.AddField(
            model_name='processedarticle',
            name='slug',
            field=models.SlugField(
                verbose_name='Slug',
                help_text='Для /news/top/<slug>/',
                max_length=220,
                blank=True,
                null=True,
                unique=False,
            ),
        ),

        migrations.AddField(
            model_name='processedarticle',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                help_text='Внутрішні теги для крос-видачі з проєктами та сервісами',
                related_name='articles',
                to='core.tag'
            ),
        ),
        migrations.AddField(
            model_name='roianalytics',
            name='cross_promotion_success_rate',
            field=models.FloatField(default=0, verbose_name='Успішність крос-промоції (%)'),
        ),
        migrations.AddField(
            model_name='roianalytics',
            name='tag_engagement_stats',
            field=models.JSONField(default=dict, verbose_name='Статистика залучення по тегах'),
        ),
        migrations.AddField(
            model_name='roianalytics',
            name='tags_assigned',
            field=models.IntegerField(default=0, verbose_name='Тегів призначено автоматично'),
        ),
        migrations.AddField(
            model_name='roianalytics',
            name='top_performing_tags',
            field=models.JSONField(default=list, verbose_name='Топ теги за ефективністю'),
        ),
        migrations.AlterField(
            model_name='aiprocessinglog',
            name='log_type',
            field=models.CharField(
                choices=[
                    ('translation', 'Переклад'),
                    ('categorization', 'Категоризація'),
                    ('analysis', 'Аналіз'),
                    ('image_generation', 'Генерація зображень'),
                    ('cta_generation', 'Генерація CTA'),
                    ('digest_generation', 'Генерація дайджесту'),
                    ('tag_assignment', 'Призначення тегів')
                ],
                max_length=20,
                verbose_name='Тип обробки'
            ),
        ),
        migrations.AlterField(
            model_name='newswidget',
            name='widget_type',
            field=models.CharField(
                choices=[
                    ('latest', 'Останні новини'),
                    ('trending', 'Популярні новини'),
                    ('category', 'По категоріях'),
                    ('featured', 'Рекомендовані'),
                    ('top_articles', 'Топ статті')
                ],
                max_length=20,
                verbose_name='Тип віджета'
            ),
        ),
        migrations.AlterField(
            model_name='processedarticle',
            name='shares_count',
            field=models.IntegerField(default=0, verbose_name='Поділитись'),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='shares_count',
            field=models.IntegerField(default=0, verbose_name='Поділились'),
        ),

        # --- КРОК 2: бекфіл slug-ів для існуючих записів ---
        migrations.RunPython(backfill_unique_slugs, migrations.RunPython.noop),

        # --- КРОК 3: вмикаємо унікальність для slug ---
        migrations.AlterField(
            model_name='processedarticle',
            name='slug',
            field=models.SlugField(
                verbose_name='Slug',
                help_text='Для /news/top/<slug>/',
                max_length=220,
                blank=True,
                null=True,
                unique=True,
            ),
        ),

        # індекси (після того, як поле вже є та заповнене)
        migrations.AddIndex(
            model_name='processedarticle',
            index=models.Index(fields=['slug'], name='news_proces_slug_4806a0_idx'),
        ),
        migrations.AddIndex(
            model_name='processedarticle',
            index=models.Index(fields=['status', 'category'], name='news_proces_status_f5ba22_idx'),
        ),
        migrations.AddIndex(
            model_name='processedarticle',
            index=models.Index(fields=['status', 'published_at'], name='news_proces_status_8870ac_idx'),
        ),
        migrations.AddIndex(
            model_name='processedarticle',
            index=models.Index(fields=['published_at'], name='news_proces_publish_878246_idx'),
        ),
        migrations.AddIndex(
            model_name='processedarticle',
            index=models.Index(fields=['is_top_article', 'article_rank'], name='news_proces_is_top__48c57d_idx'),
        ),
        migrations.AddIndex(
            model_name='processedarticle',
            index=models.Index(fields=['top_selection_date'], name='news_proces_top_sel_cf8ab5_idx'),
        ),

        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.processedarticle'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
