# Generated by Django 4.2.7 on 2025-08-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comment_delete_dashboardproxy_newssystemanalytics_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsSystemAnalytics',
        ),
        migrations.AlterField(
            model_name='processedarticle',
            name='slug',
            field=models.SlugField(blank=True, default='defoult slug', help_text='Для /news/top/<slug>/', max_length=220, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
