# Generated by Django 4.2.7 on 2025-09-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_delete_newssystemanalytics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawarticle',
            name='author',
            field=models.CharField(blank=True, max_length=500, verbose_name='Автор'),
        ),
    ]
