# Generated by Django 4.2.7 on 2025-09-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_fix_newswidget_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedarticle',
            name='ai_image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='AI зображення'),
        ),
    ]
