# Generated by Django 4.2.7 on 2025-09-17 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_processedarticle_ai_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roianalytics',
            name='ai_api_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Витрати на AI API'),
        ),
        migrations.AlterField(
            model_name='roianalytics',
            name='ai_processing_time',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Час AI обробки (годин)'),
        ),
        migrations.AlterField(
            model_name='roianalytics',
            name='articles_processed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Статей оброблено AI'),
        ),
        migrations.AlterField(
            model_name='roianalytics',
            name='content_manager_cost_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Економія на контент-менеджері'),
        ),
        migrations.AlterField(
            model_name='roianalytics',
            name='copywriter_cost_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Економія на копірайтері'),
        ),
        migrations.AlterField(
            model_name='roianalytics',
            name='images_generated',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='AI зображень згенеровано'),
        ),
        migrations.AlterField(
            model_name='roianalytics',
            name='manual_hours_saved',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Годин заощаджено (ручна робота)'),
        ),
        migrations.AlterField(
            model_name='roianalytics',
            name='net_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(50000)], verbose_name='Чиста економія'),
        ),
        migrations.AlterField(
            model_name='roianalytics',
            name='smm_specialist_cost_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Економія на SMM'),
        ),
        migrations.AlterField(
            model_name='roianalytics',
            name='social_posts_generated',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Соцмереж постів згенеровано'),
        ),
        migrations.AlterField(
            model_name='roianalytics',
            name='tags_assigned',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Тегів призначено автоматично'),
        ),
        migrations.AlterField(
            model_name='roianalytics',
            name='time_efficiency',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Ефективність часу (%)'),
        ),
        migrations.AlterField(
            model_name='roianalytics',
            name='translations_made',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Перекладів зроблено'),
        ),
    ]
