# Generated by Django 4.2.7 on 2025-09-25 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_service_cta_text_en_and_more'),
        ('news', '0014_alter_roianalytics_ai_api_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='cta_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_cta_categories', to='services.servicecategory'),
        ),
    ]
