# Generated by Django 4.2.7 on 2025-09-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_newscategory_cta_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategory',
            name='cta_link',
        ),
    ]
