# Generated by Django 4.2.7 on 2025-09-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_remove_newscategory_cta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawarticle',
            name='has_full_content',
            field=models.BooleanField(default=False, help_text='Чи спарсено повний контент через FiveFilters', verbose_name='Має повний контент'),
        ),
    ]
