# Generated by Django 4.2.7 on 2025-09-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_add_has_full_content_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='external_post_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID в соцмережі'),
        ),
    ]
