# Generated by Django 4.2.7 on 2025-09-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_external_post_id_length'),
    ]

    operations = [
    ]
