# Generated by Django 4.2.7 on 2025-08-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name_en', models.CharField(blank=True, help_text='English name', max_length=50)),
                ('name_uk', models.CharField(blank=True, help_text='Українська назва', max_length=50)),
                ('name_pl', models.CharField(blank=True, help_text='Polska nazwa', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Hex color для відображення тегу', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='CSS class або emoji для іконки', max_length=50)),
                ('category', models.CharField(choices=[('technology', '💻 Technology'), ('industry', '🏭 Industry'), ('service', '🔧 Service Type'), ('ai', '🤖 AI & ML'), ('business', '💼 Business'), ('development', '⚡ Development')], default='technology', help_text='Категорія тегу для групування', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Опис тегу')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Показувати в топі')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Скільки разів використовується')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-is_featured', '-usage_count', 'name'],
            },
        ),
    ]
