# Generated by Django 4.2.7 on 2025-09-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок сторінки', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL slug', unique=True)),
                ('title_en', models.CharField(blank=True, help_text='English title', max_length=200)),
                ('title_uk', models.CharField(blank=True, help_text='Український заголовок', max_length=200)),
                ('title_pl', models.CharField(blank=True, help_text='Polski tytuł', max_length=200)),
                ('description', models.TextField(help_text='Короткий опис')),
                ('description_en', models.TextField(blank=True, help_text='English description')),
                ('description_uk', models.TextField(blank=True, help_text='Український опис')),
                ('description_pl', models.TextField(blank=True, help_text='Polski opis')),
                ('content', models.TextField(help_text='Основний текст сторінки')),
                ('content_en', models.TextField(blank=True, help_text='English content')),
                ('content_uk', models.TextField(blank=True, help_text='Український контент')),
                ('content_pl', models.TextField(blank=True, help_text='Polski content')),
                ('featured_image', models.ImageField(blank=True, help_text='Головне зображення', null=True, upload_to='about/hero/')),
                ('featured_video', models.FileField(blank=True, help_text='Головне відео', null=True, upload_to='about/videos/')),
                ('video_thumbnail', models.ImageField(blank=True, help_text="Прев'ю для відео", null=True, upload_to='about/thumbnails/')),
                ('seo_title', models.CharField(blank=True, help_text='SEO заголовок', max_length=200)),
                ('seo_description', models.TextField(blank=True, help_text='SEO опис')),
                ('seo_keywords', models.CharField(blank=True, help_text='SEO ключові слова', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Активна сторінка')),
                ('is_featured', models.BooleanField(default=False, help_text='Рекомендована')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Відео файл', upload_to='about/videos/')),
                ('thumbnail', models.ImageField(blank=True, help_text="Прев'ю для відео", null=True, upload_to='about/thumbnails/')),
                ('title', models.CharField(blank=True, help_text='Назва відео', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Опис відео')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок відображення')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.aboutpage')),
            ],
            options={
                'verbose_name': 'About Video',
                'verbose_name_plural': 'About Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Зображення', upload_to='about/images/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt текст для зображення', max_length=200)),
                ('caption', models.CharField(blank=True, help_text='Підпис до зображення', max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок відображення')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.aboutpage')),
            ],
            options={
                'verbose_name': 'About Image',
                'verbose_name_plural': 'About Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
