# Generated by Django 4.2.7 on 2025-09-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutpage_aboutvideo_aboutimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutvideo',
            name='about_page',
        ),
        migrations.DeleteModel(
            name='AboutImage',
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='AboutVideo',
        ),
    ]
