# Generated by Django 4.2.7 on 2025-09-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aboutvideo_about_page_delete_aboutimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('heading_en', models.CharField(blank=True, max_length=200)),
                ('heading_uk', models.CharField(blank=True, max_length=200)),
                ('heading_pl', models.CharField(blank=True, max_length=200)),
                ('subheading_en', models.CharField(blank=True, max_length=300)),
                ('subheading_uk', models.CharField(blank=True, max_length=300)),
                ('subheading_pl', models.CharField(blank=True, max_length=300)),
                ('description_en', models.TextField(blank=True)),
                ('description_uk', models.TextField(blank=True)),
                ('description_pl', models.TextField(blank=True)),
                ('cta_primary_label_en', models.CharField(blank=True, max_length=120)),
                ('cta_primary_label_uk', models.CharField(blank=True, max_length=120)),
                ('cta_primary_label_pl', models.CharField(blank=True, max_length=120)),
                ('cta_primary_url', models.URLField(blank=True, help_text='Якщо пусто – відкриває модальне вікно')),
                ('cta_secondary_label_en', models.CharField(blank=True, max_length=120)),
                ('cta_secondary_label_uk', models.CharField(blank=True, max_length=120)),
                ('cta_secondary_label_pl', models.CharField(blank=True, max_length=120)),
                ('cta_secondary_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home hero',
                'verbose_name_plural': 'Home heroes',
            },
        ),
    ]
