# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_site_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Показувати цю картку на головній сторінці')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (EN)')),
                ('title_uk', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (UK)')),
                ('title_pl', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (PL)')),
                ('description_en', models.TextField(blank=True, verbose_name='Опис (EN)')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис (UK)')),
                ('description_pl', models.TextField(blank=True, verbose_name='Опис (PL)')),
                ('image', models.ImageField(blank=True, help_text='Рекомендований розмір: 600x400px', null=True, upload_to='about/', verbose_name='Зображення')),
                ('url', models.CharField(default='/about/', help_text='URL для переходу при кліку', max_length=200, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок сортування (менше = вище)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Card',
                'verbose_name_plural': 'About Cards',
                'ordering': ['order', '-updated_at'],
            },
        ),
    ]
