# Generated by Django 4.2.7 on 2025-09-22 09:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0016_remove_service_cta_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', '🥉 Базовий'), ('standard', '🥈 Стандарт'), ('premium', '🥇 Преміум'), ('enterprise', '💎 Корпоративний')], max_length=50, unique=True)),
                ('display_name_uk', models.CharField(max_length=100)),
                ('display_name_en', models.CharField(max_length=100)),
                ('display_name_pl', models.CharField(max_length=100)),
                ('description_uk', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_pl', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False, help_text="Позначити як 'Популярний'")),
            ],
            options={
                'verbose_name': 'Рівень цін',
                'verbose_name_plural': 'Рівні цін',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_from', models.DecimalField(decimal_places=2, help_text='Мінімальна ціна в USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, help_text='Максимальна ціна (якщо діапазон). Залишити пустим для фіксованої ціни', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('timeline_weeks_from', models.PositiveIntegerField(help_text='Мінімальний час в тижнях')),
                ('timeline_weeks_to', models.PositiveIntegerField(blank=True, help_text='Максимальний час в тижнях (якщо діапазон)', null=True)),
                ('features_included_uk', models.TextField(help_text='Що включено в цю ціну (українською). Кожна лінія = одна фіча')),
                ('features_included_en', models.TextField(help_text="What's included (English). Each line = one feature")),
                ('features_included_pl', models.TextField(help_text='Co jest włączone (Polish). Każda linia = jedna funkcja')),
                ('complexity_level', models.CharField(choices=[('simple', 'Простий'), ('medium', 'Середній'), ('complex', 'Складний'), ('enterprise', 'Корпоративний')], default='medium', max_length=20)),
                ('suitable_for_uk', models.TextField(blank=True, help_text='Для кого підходить цей пакет (українською)')),
                ('suitable_for_en', models.TextField(blank=True, help_text='Who this package is suitable for (English)')),
                ('suitable_for_pl', models.TextField(blank=True, help_text='Dla kogo odpowiedni jest ten pakiet (Polish)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='services.servicecategory', verbose_name='Категорія сервісу')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricingtier', verbose_name='Рівень')),
            ],
            options={
                'verbose_name': 'Ціна сервісу',
                'verbose_name_plural': 'Ціни сервісів',
                'ordering': ['service_category__title_en', 'tier__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('client_company', models.CharField(blank=True, max_length=100)),
                ('original_query', models.TextField(help_text='Оригінальний запит клієнта')),
                ('ai_analysis', models.TextField(blank=True, help_text='Аналіз AI про складність та вимоги')),
                ('pdf_generated', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('email_sent', models.BooleanField(default=False)),
                ('wants_consultation', models.BooleanField(default=False)),
                ('consultation_scheduled', models.BooleanField(default=False)),
                ('google_event_id', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новий'), ('analyzed', 'Проаналізований'), ('quoted', 'Відправлено прорахунок'), ('consulted', 'Записано на консультацію'), ('converted', 'Конвертований'), ('closed', 'Закритий')], default='new', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('service_category', models.ForeignKey(blank=True, help_text='Якщо AI зміг визначити категорію', null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory')),
                ('suggested_pricing', models.ForeignKey(blank=True, help_text='Запропоновані AI ціни', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.servicepricing')),
            ],
            options={
                'verbose_name': 'Запит на прорахунок',
                'verbose_name_plural': 'Запити на прорахунки',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddIndex(
            model_name='servicepricing',
            index=models.Index(fields=['service_category', 'tier'], name='pricing_ser_service_b1b79a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepricing',
            index=models.Index(fields=['is_active'], name='pricing_ser_is_acti_46adbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicepricing',
            unique_together={('service_category', 'tier')},
        ),
    ]
