# Generated by Django 4.2.7 on 2025-10-29 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('pesel', models.CharField(max_length=11, verbose_name='PESEL')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Дата народження')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Посада')),
                ('start_date', models.DateField(verbose_name='Дата початку праці')),
                ('contract_type', models.CharField(choices=[('umowa_o_prace', 'Umowa o pracę'), ('zlecenie', 'Zlecenie'), ('staz', 'Staż')], max_length=20, verbose_name='Тип умови')),
                ('weekly_hours', models.PositiveIntegerField(default=40, verbose_name='Години праці на тиждень')),
                ('salary_netto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата нетто (PLN)')),
                ('salary_brutto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата брутто (PLN)')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата генерації договору')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='hr/contracts/', verbose_name='PDF договору')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee', verbose_name='Працівник')),
            ],
            options={
                'verbose_name': 'Договір',
                'verbose_name_plural': 'Договори',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Годин відпрацьовано')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='hr.employee', verbose_name='Працівник')),
            ],
            options={
                'verbose_name': 'Запис табелю',
                'verbose_name_plural': 'Табель робочого часу',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
