# Generated by Django 4.2.7 on 2025-10-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='hourly_rate_brutto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ставка за годину (brutto PLN)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='salary_brutto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата брутто (PLN)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='salary_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата нетто (PLN)'),
        ),
    ]
