# Generated by Django 4.2.7 on 2025-10-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_add_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='timesheet_pdf',
            field=models.FileField(blank=True, null=True, upload_to='hr/timesheets/', verbose_name='PDF табелю'),
        ),
    ]
