# Generated by Claude Code on 2025-10-30
# This is an empty migration to satisfy Django's migration checker

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_add_timesheet_pdf'),
    ]

    operations = [
        # Empty migration - no changes needed
    ]
