# Generated by Django 4.2.7 on 2025-08-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255)),
                ('title_pl', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_uk', models.TextField()),
                ('description_pl', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons/')),
                ('seo_title', models.CharField(max_length=255)),
                ('seo_description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
