# Generated by Django 4.2.7 on 2025-08-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecategory_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=255)),
                ('answer_en', models.TextField()),
                ('question_uk', models.CharField(max_length=255)),
                ('answer_uk', models.TextField()),
                ('question_pl', models.CharField(max_length=255)),
                ('answer_pl', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
    ]
