# Generated by Django 4.2.7 on 2025-08-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255)),
                ('title_pl', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_uk', models.TextField()),
                ('description_pl', models.TextField()),
                ('seo_title', models.CharField(max_length=255)),
                ('seo_description', models.TextField()),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='services/og/')),
            ],
        ),
    ]
