# Generated by Django 4.2.7 on 2025-08-01 11:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicefeature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='seo_title',
            new_name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='seo_description',
        ),
        migrations.AddField(
            model_name='service',
            name='seo_description_en',
            field=ckeditor.fields.RichTextField(default='To be added'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_description_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_description_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_pl',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_uk',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_pl',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_uk',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='description_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='description_pl',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='description_uk',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='seo_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
