# Generated by Django 4.2.7 on 2025-08-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_seo_title_service_seo_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
