# Generated by Django 4.2.7 on 2025-08-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('services', '0009_alter_service_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-priority', '-order', '-date_created'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Показувати на головній сторінці'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок відображення'),
        ),
        migrations.AddField(
            model_name='service',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'Низький'), (2, 'Звичайний'), (3, 'Високий'), (4, 'Критичний'), (5, 'Топ сервіс')], default=2, help_text='Пріоритет сервісу для сортування'),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Внутрішні теги для крос-видачі з новинами та проєктами', related_name='services', to='core.tag'),
        ),
    ]
