# Generated by Django 4.2.7 on 2025-09-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_options_service_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
            preserve_default=False,
        ),
    ]
