# Generated by Django 4.2.7 on 2025-09-10 10:46

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aboutvideo_about_page_delete_aboutimage_and_more'),
        ('services', '0011_alter_service_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['-priority', '-order', '-date_created'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/icons/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'Низький'), (2, 'Звичайний'), (3, 'Високий'), (4, 'Критичний'), (5, 'Топ сервіс')], default=2),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='seo_description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='seo_description_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='seo_description_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='seo_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='seo_title_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='service_categories', to='core.tag'),
        ),
    ]
