# Generated by Django 4.2.7 on 2025-09-10 10:49

from django.db import migrations


def merge_service_into_category(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    Tag = apps.get_model('core', 'Tag')
    for cat in ServiceCategory.objects.all():
        qs = Service.objects.filter(category_id=cat.id).order_by('-is_featured','-priority','-date_created')
        s = qs.first()
        if not s:
            continue
        if not cat.icon and s.icon:
            cat.icon = s.icon
        if not cat.seo_title_en:
            cat.seo_title_en = getattr(s, 'seo_title_en', None)
        if not cat.seo_title_uk:
            cat.seo_title_uk = getattr(s, 'seo_title_uk', None)
        if not cat.seo_title_pl:
            cat.seo_title_pl = getattr(s, 'seo_title_pl', None)
        if not cat.seo_description_en:
            cat.seo_description_en = getattr(s, 'seo_description_en', None)
        if not cat.seo_description_uk:
            cat.seo_description_uk = getattr(s, 'seo_description_uk', None)
        if not cat.seo_description_pl:
            cat.seo_description_pl = getattr(s, 'seo_description_pl', None)
        cat.is_featured = getattr(s, 'is_featured', False) or cat.is_featured
        cat.priority = max(getattr(s, 'priority', 2) or 2, cat.priority or 2)
        cat.order = cat.order or getattr(s, 'order', 0) or 0
        if not cat.description_en:
            cat.description_en = getattr(s, 'description_en', None)
        if not cat.description_uk:
            cat.description_uk = getattr(s, 'description_uk', None)
        if not cat.description_pl:
            cat.description_pl = getattr(s, 'description_pl', None)
        cat.save()
        try:
            for t in s.tags.all():
                cat.tags.add(t)
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('core','0001_initial'),
        ('services','0012_migrate_service_to_category'),
    ]

    operations = [
        migrations.RunPython(merge_service_into_category, migrations.RunPython.noop),
    ]
