# Generated by Django 4.2.7 on 2025-09-10 11:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_merge_service_to_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='gallery_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='services/gallery/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='gallery_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='services/gallery/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='gallery_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='services/gallery/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='gallery_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='services/gallery/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='pricing_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='pricing_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='pricing_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='short_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='short_description_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='short_description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='target_audience_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='target_audience_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='target_audience_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='value_proposition_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='value_proposition_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='value_proposition_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='services/videos/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='seo_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='seo_description_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='seo_description_uk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
