# Generated by Django 4.2.7 on 2025-09-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_servicecategory_gallery_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cta_text_en',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_text_pl',
            field=models.CharField(default='Dowiedz się więcej', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_text_uk',
            field=models.CharField(default='Дізнатися більше', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_url',
            field=models.URLField(blank=True, help_text='Посилання для CTA кнопки', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Рекомендований розмір: 400x250px', null=True, upload_to='services/main/', verbose_name='Головне зображення'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_featured', 'priority'], name='services_se_is_feat_5aeb66_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['slug'], name='services_se_slug_89aee3_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['date_created'], name='services_se_date_cr_0e3860_idx'),
        ),
    ]
