# Generated by Django 4.2.7 on 2025-09-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_service_cta_text_en_service_cta_text_pl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cta_text_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cta_text_pl',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cta_text_uk',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cta_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='main_image',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='cta_text_en',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='cta_text_pl',
            field=models.CharField(default='Dowiedz się więcej', max_length=50),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='cta_text_uk',
            field=models.CharField(default='Дізнатися більше', max_length=50),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='cta_url',
            field=models.URLField(blank=True, help_text='Посилання для CTA кнопки', null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Рекомендований розмір: 400x250px', null=True, upload_to='services/main/', verbose_name='Головне зображення'),
        ),
    ]
