# Generated by Django 5.0.14 on 2025-09-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_service_cta_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Зображення для соцмереж (1200x630px)', null=True, upload_to='services/og/'),
        ),
    ]
