version: '3.8'

services:
  fullfeedrss:
    image: "heussd/fivefilters-full-text-rss:latest"
    container_name: lazysoft-fivefilters
    environment:
      - FTR_ADMIN_PASSWORD=
    volumes:
      - "rss-cache:/var/www/html/cache/rss"
    ports:
      - "8082:80" 
    restart: unless-stopped

volumes:
  rss-cache: