# Generated by Django 4.2.7 on 2025-09-17 12:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='About Lazysoft', max_length=255)),
                ('title_uk', models.CharField(default='Про Lazysoft', max_length=255)),
                ('title_pl', models.CharField(default='O Lazysoft', max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=500)),
                ('subtitle_uk', models.CharField(blank=True, max_length=500)),
                ('subtitle_pl', models.CharField(blank=True, max_length=500)),
                ('story_en', ckeditor.fields.RichTextField()),
                ('story_uk', ckeditor.fields.RichTextField()),
                ('story_pl', ckeditor.fields.RichTextField()),
                ('services_en', ckeditor.fields.RichTextField()),
                ('services_uk', ckeditor.fields.RichTextField()),
                ('services_pl', ckeditor.fields.RichTextField()),
                ('mission_en', ckeditor.fields.RichTextField()),
                ('mission_uk', ckeditor.fields.RichTextField()),
                ('mission_pl', ckeditor.fields.RichTextField()),
                ('seo_title_en', models.CharField(blank=True, max_length=255)),
                ('seo_title_uk', models.CharField(blank=True, max_length=255)),
                ('seo_title_pl', models.CharField(blank=True, max_length=255)),
                ('seo_description_en', models.TextField(blank=True, max_length=300)),
                ('seo_description_uk', models.TextField(blank=True, max_length=300)),
                ('seo_description_pl', models.TextField(blank=True, max_length=300)),
                ('gallery_image_1', models.ImageField(blank=True, null=True, upload_to='about/gallery/')),
                ('gallery_image_2', models.ImageField(blank=True, null=True, upload_to='about/gallery/')),
                ('gallery_image_3', models.ImageField(blank=True, null=True, upload_to='about/gallery/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo або інший URL', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Або завантажте відео файл', null=True, upload_to='about/videos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/images/')),
                ('alt_text_en', models.CharField(blank=True, max_length=255)),
                ('alt_text_uk', models.CharField(blank=True, max_length=255)),
                ('alt_text_pl', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.about')),
            ],
            options={
                'verbose_name': 'About Image',
                'verbose_name_plural': 'About Images',
                'ordering': ['order'],
            },
        ),
    ]
