# Generated by Django 5.0.14 on 2025-09-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Зображення для соцмереж (1200x630px)', null=True, upload_to='about/og/'),
        ),
    ]
