# Generated by Django 4.2.7 on 2025-09-23 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query_pattern', models.TextField(help_text='Типовий запит користувача')),
                ('query_variations', models.JSONField(default=list, help_text='Варіації запиту')),
                ('best_response', models.TextField(help_text='Найкраща відповідь на цей паттерн')),
                ('response_source', models.CharField(choices=[('human_feedback', 'Позитивний відгук користувача'), ('successful_conversion', 'Призвела до конверсії'), ('manual_approval', 'Схвалена вручну'), ('high_similarity', 'Висока схожість з існуючими знаннями')], max_length=50)),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Скільки разів зустрічався')),
                ('success_rate', models.FloatField(default=0.0, help_text='Відсоток успішних відповідей')),
                ('avg_user_satisfaction', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('detected', 'Виявлено'), ('pending_review', 'Очікує перевірки'), ('approved', 'Схвалено'), ('indexed', 'Додано до бази знань'), ('rejected', 'Відхилено')], default='detected', max_length=20)),
                ('detected_intent', models.CharField(blank=True, max_length=50)),
                ('related_service_categories', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Паттерн навчання',
                'verbose_name_plural': 'Паттерни навчання',
                'ordering': ['-frequency', '-success_rate', '-created_at'],
            },
        ),
    ]
