# Generated by Django 4.2.7 on 2025-09-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_learningpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
