# Generated by Django 4.2.7 on 2025-09-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_chatsession_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='detected_intent',
            field=models.CharField(choices=[('greeting', 'Привітання'), ('pricing', 'Питання про ціни'), ('services', 'Інфо про сервіси'), ('portfolio', 'Перегляд проєктів'), ('consultation', 'Запис на консультацію'), ('general', 'Загальні питання')], default='general', max_length=50),
        ),
    ]
