# Generated by Django 4.2.7 on 2025-09-26 07:32

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_alter_chatsession_detected_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingmodel',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
