# Generated by Claude Code on 2025-10-30
# This is an empty migration to satisfy Django's migration checker

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_alter_embeddingmodel_embedding'),
    ]

    operations = [
        # Empty migration - no changes needed
    ]
